name: counter
description: A package containing custom counters widget.
version: 0.1.0
homepage: https://github.com/xiaochenghua/counter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  assets_scanner: ^2.0.0
  build_runner: ^2.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/
